# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqnl4IZbyQn8S-K0r4ltkBzuxfUkAfw8
"""



"""## Import Libariries"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

"""## Read Data"""

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_excel("/content/drive/MyDrive/Renty/GradProject_final_1.xlsx")

df.head()

"""## Perform EDA"""

df.info()

df.describe()

print(df.isnull().sum().sum())

print(df.duplicated().sum())

"""### Analyzing Temporal Features"""

# Convert date columns to datetime objects if they are not already
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df['StockDate'] = pd.to_datetime(df['StockDate'])

# Analyze the number of orders over time
orders_over_time = df.groupby(df['OrderDate'].dt.to_period('M')).size()
orders_over_time.index = orders_over_time.index.to_timestamp()

plt.figure(figsize=(12, 6))
orders_over_time.plot()
plt.title('Number of Orders Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Orders')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Analyze the number of stock entries over time
stock_over_time = df.groupby(df['StockDate'].dt.to_period('M')).size()
stock_over_time.index = stock_over_time.index.to_timestamp()

plt.figure(figsize=(12, 6))
stock_over_time.plot()
plt.title('Number of Stock Entries Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Stock Entries')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Exploring Relationships Between Numerical Features (Heatmap)"""

# Explore relationships between numerical features using a heatmap
numerical_cols = ['IncomeCategory', 'AnnualIncome', 'TotalChildren', 'OrderQuantity']
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""### Insights from the Correlation Heatmap

The heatmap of the correlation matrix for the numerical features (`OrderQuantity`, `AnnualIncome`, `TotalChildren`, and `IncomeCategory`) reveals the following:

*   There is a very weak negative correlation between `OrderQuantity` and `AnnualIncome` (-0.02).
*   There is a weak positive correlation between `OrderQuantity` and `TotalChildren` (0.04).
*   There is a very weak negative correlation between `OrderQuantity` and `IncomeCategory` (-0.02).
*   As expected, there is a strong positive correlation between `AnnualIncome` and `IncomeCategory` (0.84), as `IncomeCategory` is likely derived from `AnnualIncome`.
*   There is a weak positive correlation between `AnnualIncome` and `TotalChildren` (0.21).
*   There is a weak positive correlation between `TotalChildren` and `IncomeCategory` (0.24).

Overall, the heatmap suggests that there are no strong linear correlations between `OrderQuantity` and the other numerical features (`AnnualIncome`, `TotalChildren`, `IncomeCategory`). This indicates that these numerical user demographic features, while potentially useful in other ways, do not have a strong linear relationship with the number of items ordered. The strongest correlations are observed between the income-related features (`AnnualIncome` and `IncomeCategory`) and `TotalChildren`, which might indicate some demographic patterns within the dataset.

### Exploring Relationships Between Features
"""

# Explore relationships between numerical features
numerical_cols = ['OrderQuantity', 'AnnualIncome', 'TotalChildren']
sns.pairplot(df[numerical_cols])
plt.suptitle('Pairwise Relationships of Numerical Features', y=1.02)
plt.show()

"""### Analyzing Numerical Features"""

# Display descriptive statistics for numerical columns
display(df.describe())

# Visualize the distribution of numerical columns
numerical_cols = ['OrderQuantity', 'AnnualIncome', 'TotalChildren']
for col in numerical_cols:
    plt.figure(figsize=(8, 6))
    sns.histplot(data=df, x=col, kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.show()

"""### Explore relationships between categorical user features and OrderQuantity

"""

# Explore relationships between categorical user features and OrderQuantity
categorical_user_cols = ['MaritalStatus', 'Gender', 'EducationLevel', 'Occupation', 'HomeOwner']

for col in categorical_user_cols:
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x=col, y='OrderQuantity', palette='viridis', hue=col, legend=False)
    plt.title(f'Order Quantity by {col}')
    plt.xlabel(col)
    plt.ylabel('Order Quantity')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""### Analyzing Categorical Features"""

# Visualize the distribution of categorical columns
categorical_cols = ['MaritalStatus', 'Gender', 'EducationLevel', 'Occupation', 'HomeOwner']
for col in categorical_cols:
    plt.figure(figsize=(8, 6))
    sns.countplot(data=df, y=col, order=df[col].value_counts().index, palette='viridis', hue=col, legend=False)
    plt.title(f'Distribution of {col}')
    plt.xlabel('Count')
    plt.ylabel(col)
    plt.show()

"""## Insights and Conclusions from EDA

### Numerical Feature Analysis

*   **OrderQuantity:** The distribution of `OrderQuantity` is heavily skewed towards lower values, with most orders consisting of only 1 or 2 items. This suggests that customers typically purchase a small number of items in a single order. The descriptive statistics confirm this, with a mean of around 1.5 and a maximum of 3.
*   **AnnualIncome:** The distribution of `AnnualIncome` appears to be somewhat multimodal, with peaks around certain income brackets. The descriptive statistics show a wide range of incomes, from \$10,000 to \$170,000, with a mean around \$60,000.
*   **TotalChildren:** The distribution of `TotalChildren` shows that a significant portion of customers have 0 or 1 child, with fewer customers having more children. The maximum number of children is 5.

### Categorical Feature Analysis

*   **MaritalStatus:** The distribution of `MaritalStatus` shows that there are more married customers than single customers in the dataset.
*   **Gender:** The distribution of `Gender` indicates a relatively balanced representation of male and female customers.
*   **EducationLevel:** The distribution of `EducationLevel` shows a diverse range of educational backgrounds among customers, with 'Partial College' and 'Bachelors' being the most frequent.
*   **Occupation:** The distribution of `Occupation` reveals that 'Professional' and 'Skilled Manual' are the most common occupations among customers.
*   **HomeOwner:** The distribution of `HomeOwner` shows that there are more customers who own their homes than those who do not.

### Temporal Feature Analysis

*   **Orders Over Time:** The plot of the number of orders over time shows a clear increasing trend, particularly from mid-2021 onwards. There appears to be some seasonality, with potential peaks at certain times of the year.
*   **Stock Entries Over Time:** The plot of stock entries over time also shows fluctuations, which seem to generally follow the trend of orders, although with some variations.

### Relationship Analysis (Numerical Features)

*   The pairwise scatter plots of numerical features (`OrderQuantity`, `AnnualIncome`, `TotalChildren`) do not show strong linear relationships between these variables. There might be some subtle patterns or clusters, but no clear correlations are immediately apparent from these plots.

### Relationship Analysis (Categorical User Features and OrderQuantity)

*   The box plots show some variations in `OrderQuantity` across different categories of user features. For example, there might be slight differences in the median `OrderQuantity` between different marital statuses, genders, education levels, occupations, and home ownership statuses. However, the differences in the overall distributions (as shown by the box plots) suggest that these categorical features might have some influence on order quantity, but it's not a very strong or simple relationship.

### Relationship Analysis (Item and User Features)

*   The box plot showing `OrderQuantity` by `ModelName` and `Gender` for the top 10 models provides insights into how the popularity of certain models varies between male and female customers. There are visible differences in the distribution of `OrderQuantity` for some models based on gender, suggesting that gender can be a relevant factor in understanding product preferences and order quantities for these specific models.

**Overall Conclusions for LightFM:**

Based on this EDA, we have identified several potential features that can be used in the LightFM recommendation system. User features such as `MaritalStatus`, `Gender`, `AnnualIncome`, `TotalChildren`, `EducationLevel`, `Occupation`, and `HomeOwner` can help in building user embeddings. Item features like `ModelName` and `ProductDescription` can contribute to item embeddings. The `OrderQuantity` can serve as the interaction strength. While the temporal analysis didn't reveal very strong seasonal patterns, it's worth considering if engineered temporal features could still be beneficial. The relationships explored suggest that user demographics and item types can influence purchasing behavior and order quantities, which aligns with the goal of a personalized recommendation system. Further feature engineering and model experimentation will be needed to determine the most effective set of features for the LightFM model.
"""