# -*- coding: utf-8 -*-
"""get_recommendations_for_input_user

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqnl4IZbyQn8S-K0r4ltkBzuxfUkAfw8
"""



"""## Load the saved model and artifacts"""

import pickle

def load_model_artifacts(filepath='renty_lightfm_model_artifacts.pkl'):
    """Loads the LightFM model and associated artifacts from a pickle file."""
    with open(filepath, 'rb') as f:
        artifacts = pickle.load(f)
    print(f"Model and artifacts loaded successfully from {filepath}")
    return artifacts['model'], artifacts['dataset'], artifacts['user_features'], artifacts['item_features']


loaded_model, loaded_dataset, loaded_user_features, loaded_item_features = load_model_artifacts(filepath='renty_lightfm_model_artifacts.pkl')

print("Model and artifacts loaded successfully!")

def get_recommendations_for_input_user(user_id_input, model, dataset, user_features, item_features, df, n_recommendations=10):
    """
    Takes a user ID input and provides recommendations using the loaded LightFM model.

    Args:
        user_id_input: The CustomerKey of the user for whom to generate recommendations.
        model: The trained LightFM model.
        dataset: The LightFM Dataset object.
        user_features: The user features matrix.
        item_features: The item features matrix.
        df: The original pandas DataFrame containing user purchase history.
        n_recommendations: The number of recommendations to generate.
    """
    print(f"\nAttempting to get recommendations for user ID: {user_id_input}")

    try:
        user_id_input = int(user_id_input)
    except ValueError:
        print(f"Invalid user ID format: {user_id_input}. User ID should be an integer.")
        return

    # Use the existing get_recommendations function
    recommendations = get_recommendations(
        model, user_id_input, dataset, user_features, item_features,
        df, n_recommendations=n_recommendations, filter_already_purchased=True
    )

    if recommendations is not None and not recommendations.empty:
        print(f"\n Recommendations for user {user_id_input}:")
        display(recommendations)
    elif recommendations is not None and recommendations.empty:
         print(f"\nNo new recommendations found for user {user_id_input} (already purchased all top items).")
    else:
        # The get_recommendations function already prints a message if the user is not found
        pass

sample_user_id = df['CustomerKey'].sample(1).iloc[0] # Get a random user ID from the original dataframe
# Read integer input
try:
    sample_user_id = input("Please enter a User ID: ")
    sample_user_id = int(sample_user_id)
except ValueError:
    print(f"Invalid input. '{sample_user_id}' is not a valid integer.")
get_recommendations_for_input_user(sample_user_id, loaded_model, loaded_dataset, loaded_user_features, loaded_item_features, df)

# get_recommendations_for_input_user(14574, loaded_model, loaded_dataset, loaded_user_features, loaded_item_features, df)