# -*- coding: utf-8 -*-
"""MAIN_EXECUTION_PIPELINE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqnl4IZbyQn8S-K0r4ltkBzuxfUkAfw8
"""



"""# MAIN EXECUTION PIPELINE"""

def main(filepath):
    """Execute complete improved recommendation system pipeline"""

    print(" INITIATING IMPROVED LIGHTFM RECOMMENDER SYSTEM")
    print("=" * 80)

    # Step 1: Load and preprocess data
    df = load_and_preprocess_data(filepath)

    # Step 2: Advanced feature engineering
    df = engineer_features(df)

    # Step 3: Text feature extraction
    df, text_feature_cols = extract_text_features(df, max_features=50)

    # Step 4: Prepare LightFM data
    dataset, user_features, item_features = prepare_lightfm_data(df, text_feature_cols)

    # Step 5: Create train/test splits
    train_interactions, test_interactions, train_weights, test_weights = \
        create_interaction_matrices(df, dataset)

    # Step 6: Hyperparameter tuning with regularization
    best_params, results_df = extended_hyperparameter_search(
        train_interactions, test_interactions,
        user_features, item_features, train_weights
    )

    # Train final model with best parameters
    print("\n" + "=" * 80)
    print(" TRAINING FINAL MODEL WITH OPTIMIZED PARAMETERS")
    print("=" * 80)

    final_model = train_lightfm_model(
        train_interactions, user_features, item_features,
        train_weights=train_weights,
        loss=best_params['loss'],
        no_components=best_params['no_components'],
        learning_rate=best_params['learning_rate'],
        item_alpha=best_params['item_alpha'],
        user_alpha=best_params['user_alpha'],
        epochs=60,
        num_threads=4,
        verbose=True
    )

    # Step 7: Comprehensive evaluation
    evaluation_results = evaluate_model(
        final_model, train_interactions, test_interactions,
        user_features, item_features
    )

    # Step 8: Generate recommendations - FIXED: pass final_model explicitly
    display_user_recommendations(
        df, final_model, dataset, user_features, item_features,
        n_recommendations=10
    )

    # Step 9: Visualization and analysis
    baseline_results = {
        'precision@5': 0.15, 'precision@10': 0.12, 'precision@20': 0.08,
        'recall@5': 0.08, 'recall@10': 0.15, 'recall@20': 0.22,
        'train_auc': 0.92, 'test_auc': 0.75, 'overfitting_gap': 0.17
    }

    plot_comparison_results(baseline_results, evaluation_results)
    plot_hyperparameter_analysis(results_df)

    print("\n" + "=" * 80)
    print(" IMPROVED RECOMMENDER SYSTEM PIPELINE COMPLETED!")
    print("=" * 80)

    return final_model, dataset, user_features, item_features, df, evaluation_results


# ============================================================================
# EXECUTE THE IMPROVED PIPELINE
# ============================================================================

if __name__ == "__main__":
    # Update this path to your file location
    filepath = "/content/drive/MyDrive/Renty/GradProject_final_1.xlsx"

    try:
        model, dataset, user_features, item_features, df, results = main(filepath)

        print("\n IMPROVED SYSTEM FEATURES SUMMARY:")
        print("-" * 80)
        print("✓ Advanced feature engineering with RFM-based customer segmentation")
        print("✓ TF-IDF text features from product descriptions")
        print("✓ Comprehensive regularization to reduce overfitting")
        print("✓ Temporal train/test splitting for realistic evaluation")
        print("✓ Enhanced visualization and performance analysis")
        print("✓ Customer segmentation (Bronze/Silver/Gold/Platinum)")
        print("✓ Item popularity categorization (Niche/Viral/etc.)")

        print(f"\n FINAL PERFORMANCE:")
        print(f"  • Test AUC: {results['test_auc']:.4f}")
        print(f"  • Precision@10: {results['precision@10']:.4f}")
        print(f"  • Overfitting Gap: {results['overfitting_gap']:.4f}")

    except Exception as e:
        print(f" Error in pipeline execution: {e}")
        import traceback
        traceback.print_exc()