# -*- coding: utf-8 -*-
"""Save_the_final_model_ and_artifacts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqnl4IZbyQn8S-K0r4ltkBzuxfUkAfw8

## Save the final model and artifacts
"""

import pickle

def save_model_artifacts(model, dataset, user_features, item_features, filepath='renty_lightfm_model_artifacts.pkl'):
    """Saves the LightFM model and associated artifacts to a pickle file."""
    artifacts = {
        'model': model,
        'dataset': dataset,
        'user_features': user_features,
        'item_features': item_features
    }
    with open(filepath, 'wb') as f:
        pickle.dump(artifacts, f)
    print(f"Model and artifacts saved successfully to {filepath}")

save_model_artifacts(model, dataset, user_features, item_features, filepath='renty_lightfm_model_artifacts.pkl')